{{- /*
 Use sprig semver function to do the version comparison
https://github.com/helm/charts/issues/3002
https://masterminds.github.io/sprig/semver.html 
*/ -}}
{{- if gt (semver .Values.kyma.version | (semver "1.11.0-0").Compare) 0 -}}
apiVersion: eventing.kyma-project.io/v1alpha1
kind: Subscription
metadata:
  name: {{ include "fsm-extension-installer.eventSubscriptionPrefix" . }}-install-ev-subscription
  namespace: {{ .Release.Namespace }}
spec:
  endpoint: http://{{ include "fsm-extension-installer.fullname" . }}.{{ .Release.Namespace }}:{{ .Values.service.port }}/api/fsm-extension-installer/v1/install
  event_type: extensioncatalog.extension.install.requested
  event_type_version: v1
  include_subscription_name_header: true
  source_id: {{ required "Application Name must be provided!" .Values.appName }}
---
apiVersion: eventing.kyma-project.io/v1alpha1
kind: Subscription
metadata:
  name: {{ include "fsm-extension-installer.eventSubscriptionPrefix" . }}-uninstall-ev-subscription
  namespace: {{ .Release.Namespace }}
spec:
  endpoint: http://{{ include "fsm-extension-installer.fullname" . }}.{{ .Release.Namespace }}:{{ .Values.service.port }}/api/fsm-extension-installer/v1/uninstall
  event_type: extensioncatalog.extension.uninstall.requested
  event_type_version: v1
  include_subscription_name_header: true
  source_id: {{ required "Application Name must be provided!" .Values.appName }}
---
apiVersion: eventing.kyma-project.io/v1alpha1
kind: Subscription
metadata:
  name: {{ include "fsm-extension-installer.eventSubscriptionPrefix" . }}-upgrade-ev-subscription
  namespace: {{ .Release.Namespace }}
spec:
  endpoint: http://{{ include "fsm-extension-installer.fullname" . }}.{{ .Release.Namespace }}:{{ .Values.service.port }}/api/fsm-extension-installer/v1/upgrade
  event_type: extensioncatalog.extension.upgrade.requested
  event_type_version: v1
  include_subscription_name_header: true
  source_id: {{ required "Application Name must be provided!" .Values.appName }}
{{- end }}


{{- if lt (semver .Values.kyma.version | (semver "1.11.0-0").Compare) 0 -}}
apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: {{ include "fsm-extension-installer.eventSubscriptionPrefix" . }}-install-ev-subscription
  namespace: {{ .Release.Namespace }}
spec:
  broker: default
  filter:
    attributes:
      eventtypeversion: v1
      source: {{ required "Application Name must be provided!" .Values.appName }}
      type: extensioncatalog.extension.install.requested
  subscriber:
    uri: http://{{ include "fsm-extension-installer.fullname" . }}.{{ .Release.Namespace }}:{{ .Values.service.port }}/api/fsm-extension-installer/v1/install/
---
apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: {{ include "fsm-extension-installer.eventSubscriptionPrefix" . }}-uninstall-ev-subscription
  namespace: {{ .Release.Namespace }}
spec:
  broker: default
  filter:
    attributes:
      eventtypeversion: v1
      source: {{ required "Application Name must be provided!" .Values.appName }}
      type: extensioncatalog.extension.uninstall.requested
  subscriber:
    uri: http://{{ include "fsm-extension-installer.fullname" . }}.{{ .Release.Namespace }}:{{ .Values.service.port }}/api/fsm-extension-installer/v1/uninstall/
---
apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: {{ include "fsm-extension-installer.eventSubscriptionPrefix" . }}-upgrade-ev-subscription
  namespace: {{ .Release.Namespace }}
spec:
  broker: default
  filter:
    attributes:
      eventtypeversion: v1
      source: {{ required "Application Name must be provided!" .Values.appName }}
      type: extensioncatalog.extension.upgrade.requested
  subscriber:
    uri: http://{{ include "fsm-extension-installer.fullname" . }}.{{ .Release.Namespace }}:{{ .Values.service.port }}/api/fsm-extension-installer/v1/upgrade/
{{- end }}
