name: fsm-extension-installer
version: 0.3.0
id: 57b51964-e910-44b3-8fe1-245fc50e24d7
description: "A simple addon to enable installing FSM extension on Kyma"
displayName: "FSM Extension Installer For Kyma"
providerDisplayName: "FSM"
documentationURL: https://github.com/SAP-samples/fsm-extension-installer-kyma/blob/master/README.md
tags: FSM, extension-installer, 0.3.0, broker
