name: fsm-extension-installer
version: 0.2.1
id: ca0ebdb6-216b-465f-8fdf-499f4aecfcce
description: "A simple addon to enable installing FSM extension on Kyma"
displayName: "FSM Extension Installer For Kyma"
providerDisplayName: "FSM"
documentationURL: https://github.com/SAP-samples/fsm-extension-installer-kyma/blob/master/README.md
tags: FSM, extension-installer, 0.2.1, broker
