name: fsm-extension-installer
version: 0.1.2
id: 01e28441-08f1-42d2-af34-d04a46444c22
description: "A simple addon to enable installing FSM extension on Kyma"
displayName: "FSM Extension Installer For Kyma"
providerDisplayName: "FSM"
documentationURL: https://github.com/SAP-samples/fsm-extension-installer-kyma/blob/master/README.md
tags: FSM, extension-installer, 0.1.2, broker
