name: fsm-extension-installer
version: 0.1.2
id: e186592b-c5d9-41ad-88a2-92e5692283d9
description: "A simple addon to enable installing FSM extension on Kyma"
displayName: "FSM Extension Installer For Kyma"
providerDisplayName: "FSM"
documentationURL: https://github.com/SAP-samples/fsm-extension-installer-kyma/blob/master/README.md
tags: FSM, extension-installer, 0.1.2, broker
