name: fsm-extension-installer
version: 0.3.1
id: 8027b5a4-0a77-4a1e-877b-8e2bef48a09a
description: "A simple addon to enable installing FSM extension on Kyma"
displayName: "FSM Extension Installer For Kyma"
providerDisplayName: "FSM"
documentationURL: https://github.com/SAP-samples/fsm-extension-installer-kyma/blob/master/README.md
tags: FSM, extension-installer, 0.3.1, broker
