name: fsm-extension-installer
version: 0.3.1
id: 85394319-a338-4a1c-8000-4f93f52f5867
description: "A simple addon to enable installing FSM extension on Kyma"
displayName: "FSM Extension Installer For Kyma"
providerDisplayName: "FSM"
documentationURL: https://github.com/SAP-samples/fsm-extension-installer-kyma/blob/master/README.md
tags: FSM, extension-installer, 0.3.1, broker
