{{- if lt .Values.kyma.version "1.11" -}}
apiVersion: eventing.kyma-project.io/v1alpha1
kind: Subscription
metadata:
  name: {{ include "fsm-extension-installer.fullname" . }}-install-ev-subscription
  namespace: {{ .Release.Namespace }}
spec:
  endpoint: http://{{ include "fsm-extension-installer.fullname" . }}.{{ .Release.Namespace }}:{{ .Values.service.port }}/api/fsm-extension-installer/v1/install
  event_type: extensioncatalog.extension.install.requested
  event_type_version: v1
  include_subscription_name_header: true
  source_id: {{ .Values.appName }}
---
apiVersion: eventing.kyma-project.io/v1alpha1
kind: Subscription
metadata:
  name: {{ include "fsm-extension-installer.fullname" . }}-uninstall-ev-subscription
  namespace: {{ .Release.Namespace }}
spec:
  endpoint: http://{{ include "fsm-extension-installer.fullname" . }}.{{ .Release.Namespace }}:{{ .Values.service.port }}/api/fsm-extension-installer/v1/uninstall
  event_type: extensioncatalog.extension.uninstall.requested
  event_type_version: v1
  include_subscription_name_header: true
  source_id: {{ .Values.appName }}
---
apiVersion: eventing.kyma-project.io/v1alpha1
kind: Subscription
metadata:
  name: {{ include "fsm-extension-installer.fullname" . }}-upgrade-ev-subscription
  namespace: {{ .Release.Namespace }}
spec:
  endpoint: http://{{ include "fsm-extension-installer.fullname" . }}.{{ .Release.Namespace }}:{{ .Values.service.port }}/api/fsm-extension-installer/v1/upgrade
  event_type: extensioncatalog.extension.upgrade.requested
  event_type_version: v1
  include_subscription_name_header: true
  source_id: {{ .Values.appName }}
{{- end }}


{{- if gt .Values.kyma.version "1.11" -}}
apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: {{ include "fsm-extension-installer.fullname" . }}-install-ev-subscription
  namespace: {{ .Release.Namespace }}
spec:
  broker: default
  filter:
    attributes:
      eventtypeversion: v1
      source: {{ .Values.appName }}
      type: extensioncatalog.extension.install.requested
  subscriber:
    uri: http://{{ include "fsm-extension-installer.fullname" . }}.{{ .Release.Namespace }}:{{ .Values.service.port }}/api/fsm-extension-installer/v1/install/
---
apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: {{ include "fsm-extension-installer.fullname" . }}-uninstall-ev-subscription
  namespace: {{ .Release.Namespace }}
spec:
  broker: default
  filter:
    attributes:
      eventtypeversion: v1
      source: {{ .Values.appName }}
      type: extensioncatalog.extension.uninstall.requested
  subscriber:
    uri: http://{{ include "fsm-extension-installer.fullname" . }}.{{ .Release.Namespace }}:{{ .Values.service.port }}/api/fsm-extension-installer/v1/uninstall/
---
apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: {{ include "fsm-extension-installer.fullname" . }}-upgrade-ev-subscription
  namespace: {{ .Release.Namespace }}
spec:
  broker: default
  filter:
    attributes:
      eventtypeversion: v1
      source: {{ .Values.appName }}
      type: extensioncatalog.extension.upgrade.requested
  subscriber:
    uri: http://{{ include "fsm-extension-installer.fullname" . }}.{{ .Release.Namespace }}:{{ .Values.service.port }}/api/fsm-extension-installer/v1/upgrade/
{{- end }}
